### ISSUE TITLE
Cloudflare roadmap

### ISSUE THREAD

**Issue by aletson** [aletson/votefinder-web#132]
- [ ] determine cacheable page paths - e.g., player pages, game pages - versus the dynamic stuff like what gets JavaScript loaded
- [ ] determine votefinder cookies to pass through
- [ ] create distribution with settings for this - see https://aws.amazon.com/blogs/startups/how-to-accelerate-your-wordpress-site-with-amazon-cloudfront/ for examples of differing TTL based on path 
- [ ] migrate beta DNS to new alias records
- [ ] test
- [ ] migrate prod to new alias records
- [ ] test
